--Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS Total_Customers
FROM gold.dim_customer
GROUP BY country
ORDER BY Total_Customers DESC

--Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS Total_Customers
FROM gold.dim_customer
GROUP BY gender
ORDER BY Total_Customers DESC

--Find total products by category
SELECT 
category_name,
COUNT(product_key) AS Total_Products
FROM gold.dim_product
GROUP BY category_name
ORDER BY Total_Products DESC

--What is the average costs in each category?
SELECT 
category_name,
AVG(cost) AS Average_Cost
FROM gold.dim_product
GROUP BY category_name
ORDER BY Average_Cost DESC

-- What is the total revenue generated for each category?
SELECT
p.category_name,
--P.subcategory,
COUNT(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_product p
ON		  f.product_key = p.product_key
GROUP BY p.category_name --, p.subcategory
ORDER BY Total_revenue DESC
--Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold. fact_sales f
LEFT JOIN gold.dim_customer c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold. fact_sales f
LEFT JOIN gold.dim_customer c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC
